/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidad.vista;

/**
 *
 * @author cesar
 */
public class PrincipalSGULP extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalSGULP.class.getName());
   
    private static final String RUTA_FONDO = "/imagen/ulpgob.jpg";
    
    public PrincipalSGULP() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane() {
            private final java.awt.Image img = new javax.swing.ImageIcon(getClass().getResource("/imagen/ulpgob.jpg")).getImage();

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AlumnoCargar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MateriaCargar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        jmSalir.setText("Salir");
        jMenu1.add(jmSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alumnos");
        jMenu2.addActionListener(this::jMenu2ActionPerformed);

        AlumnoCargar.setText("Gestión de Alumnos");
        AlumnoCargar.addActionListener(this::AlumnoCargarActionPerformed);
        jMenu2.add(AlumnoCargar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Materias");

        MateriaCargar.setText("Gestion de Materias");
        MateriaCargar.addActionListener(this::MateriaCargarActionPerformed);
        jMenu3.add(MateriaCargar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void AlumnoCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnoCargarActionPerformed
       escritorio.removeAll();
        escritorio.repaint();
        AlumnoCargar vistaAlumno = new AlumnoCargar();
        vistaAlumno.setVisible(true);
        escritorio.add(vistaAlumno);
        try {
            vistaAlumno.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AlumnoCargarActionPerformed

    private void MateriaCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriaCargarActionPerformed
       escritorio.removeAll();
        escritorio.repaint();
        MateriaCargar vistaMateria = new MateriaCargar();
        vistaMateria.setVisible(true);
        escritorio.add(vistaMateria);
        try {
            vistaMateria.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MateriaCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrincipalSGULP().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlumnoCargar;
    private javax.swing.JMenuItem MateriaCargar;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
