/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidad.vista;

/**
 *
 * @author cesar
 */
public class PrincipalSGULP extends javax.swing.JFrame {
    private PersonalizadoEscritorio jdpEscritorio;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalSGULP.class.getName());
        
    /**
     * Creates new form PrincipalSGULP
     */
    public PrincipalSGULP() {
        initComponents();
        jdpEscritorio = new PersonalizadoEscritorio();
        this.setContentPane(jdpEscritorio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiCargarAlumno = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiMateria = new javax.swing.JMenuItem();
        jmiCursada = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jMenu1.setText("Menu");

        jmSalir.setText("Salir");
        jMenu1.add(jmSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alumnos");
        jMenu2.addActionListener(this::jMenu2ActionPerformed);

        jmiCargarAlumno.setText("Cargar");
        jmiCargarAlumno.addActionListener(this::jmiCargarAlumnoActionPerformed);
        jMenu2.add(jmiCargarAlumno);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consulta");

        jmiMateria.setText("Materias");
        jmiMateria.addActionListener(this::jmiMateriaActionPerformed);
        jMenu3.add(jmiMateria);

        jmiCursada.setText("Cursada / Inscripción");
        jMenu3.add(jmiCursada);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jmiCargarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarAlumnoActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        AlumnoCargar alc = new AlumnoCargar();
        alc.setVisible(true);
        jdpEscritorio.add(alc);
    }//GEN-LAST:event_jmiCargarAlumnoActionPerformed

    private void jmiMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMateriaActionPerformed
        // TODO add your handling code here:
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        MateriaCargar mc = new MateriaCargar();
        mc.setVisible(true);
        jdpEscritorio.add(mc);
    }//GEN-LAST:event_jmiMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrincipalSGULP().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmSalir;
    private javax.swing.JMenuItem jmiCargarAlumno;
    private javax.swing.JMenuItem jmiCursada;
    private javax.swing.JMenuItem jmiMateria;
    // End of variables declaration//GEN-END:variables
}
